version: 2

before:
  hooks:
    # Run tests before building
    - go test ./...
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: ramp
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'

brews:
  - repository:
      owner: FreedomForeverSolar
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/FreedomForeverSolar/ramp
    description: "CLI tool for managing multi-repository development workflows using git worktrees"
    license: MIT
    test: |
      system "#{bin}/ramp", "--help"
    install: |
      bin.install "ramp"

release:
  github:
    owner: FreedomForeverSolar
    name: ramp
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }} ({{ .Date }})

    Welcome to this new release of Ramp!
  footer: |
    ## Installation

    ### Homebrew (macOS/Linux)
    ```bash
    brew install freedomforeversolar/tools/ramp
    ```

    ### Manual Installation
    Download the appropriate binary for your platform from the assets below and add it to your PATH.

    ---

    **Full Changelog**: https://github.com/FreedomForeverSolar/ramp/compare/{{ .PreviousTag }}...{{ .Tag }}
