package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"

	"ramp/cmd"
	"github.com/spf13/cobra/doc"
)

func main() {
	// Get the docs directory path
	docsDir := filepath.Join("docs", "commands")

	// Create the commands directory if it doesn't exist
	if err := os.MkdirAll(docsDir, 0755); err != nil {
		log.Fatalf("Failed to create docs directory: %v", err)
	}

	// Get the root command
	rootCmd := cmd.GetRootCmd()

	// Configure identity for link handling
	identity := func(s string) string { return s }
	emptyStr := func(s string) string { return "" }

	// Generate markdown documentation
	if err := doc.GenMarkdownTreeCustom(rootCmd, docsDir, emptyStr, identity); err != nil {
		log.Fatalf("Failed to generate documentation: %v", err)
	}

	// Strip date lines from generated files to avoid timezone-related CI failures
	dateLineRegex := regexp.MustCompile(`(?m)^###### Auto generated by spf13/cobra.*\n?`)
	files, err := os.ReadDir(docsDir)
	if err != nil {
		log.Fatalf("Failed to read docs directory: %v", err)
	}

	for _, file := range files {
		if file.IsDir() {
			continue
		}
		filePath := filepath.Join(docsDir, file.Name())
		content, err := os.ReadFile(filePath)
		if err != nil {
			log.Fatalf("Failed to read %s: %v", filePath, err)
		}
		cleaned := dateLineRegex.ReplaceAll(content, nil)
		if err := os.WriteFile(filePath, cleaned, 0644); err != nil {
			log.Fatalf("Failed to write %s: %v", filePath, err)
		}
	}

	fmt.Printf("✅ Command documentation generated in %s/\n", docsDir)

	fmt.Println("\nGenerated files:")
	for _, file := range files {
		if !file.IsDir() {
			fmt.Printf("  - %s\n", file.Name())
		}
	}
}
